name: api_local_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  #path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  json_annotation: ^4.8.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
